### ISSUE TITLE
identify on cytomine-dev-os

### ISSUE THREAD

**Issue by stevben** [cytomine/Cytomine-IMS#7]
identify -verbose /opt/cytomine/testdata/CMU-1.ndpi 

never finish. why ?

**Comment by stevben** [comment]
Auto-fix ?

**Comment by geektortoise** [comment]
It is slow but it ends.

It is slow due to these warnings.
identify.im6: Invalid TIFF directory; tags are not sorted in ascending order. `TIFFReadDirectoryCheckOrder' @ warning/tiff.c/TIFFWarnings/768.
identify.im6: Unknown field with tag 65420 (0xff8c) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
identify.im6: Unknown field with tag 65421 (0xff8d) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
identify.im6: Unknown field with tag 65422 (0xff8e) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
identify.im6: Unknown field with tag 65423 (0xff8f) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
identify.im6: Unknown field with tag 65424 (0xff90) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
identify.im6: Unknown field with tag 65425 (0xff91) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
identify.im6: Unknown field with tag 65426 (0xff92) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
identify.im6: Unknown field with tag 65428 (0xff94) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.

**Comment by stevben** [comment]
Comme quoi faut pas trop chercher parfois...
